from tkinter import *
from tkinter import ttk

new_window = Tk()

notebook = ttk.Notebook(new_window)
tab1 = Frame(notebook)
tab2 = Frame(notebook)
tab3 = Frame(notebook)
tab4 = Frame(notebook)

notebook.add(tab1, text="Personal info")
notebook.add(tab2, text="Personal Description")
notebook.add(tab3, text="Carer information")
notebook.add(tab4, text="Daily job description")
notebook.grid(column=0, row=0)

icon = PhotoImage(file="pinfo.png")
new_window.iconphoto(True, icon)
new_window.geometry("430x430")
new_window.title("Personal info")

label1 = Label(tab1, text="Personal info:", font=("Arial", 30, "bold"))
label1.grid(row=0, column=0)
label2 = Label(tab1, text="First Name: Bogdan", font=("Arial", 15, "bold"))
label2.grid(row=1, column=0, sticky="w")
label3 = Label(tab1, text="Last Name: Marian", font=("Arial", 15, "bold"))
label3.grid(row=2, column=0, sticky="w")
label4 = Label(tab1, text="Age: 33", font=("Arial", 15, "bold"))
label4.grid(row=3, column=0, sticky="w")
label5 = Label(tab1, text="---------------------------", font=("Arial", 15, "bold"))
label5.grid(row=4, column=0, sticky="w")
label6 = Label(tab1, text="Nationality: Romanian", font=("Arial", 15, "bold"))
label6.grid(row=6, column=0, sticky="w")
label7 = Label(tab1, text="Profession: Laser Marking Engineer", font=("Arial", 15, "bold"))
label7.grid(row=7, column=0, sticky="w")
label8 = Label(tab1, text="Sex: M", font=("Arial", 15, "bold"))
label8.grid(row=5, column=0, sticky="w")
label9 = Label(tab1, text="---------------------------", font=("Arial", 15, "bold"))
label9.grid(row=8, column=0, sticky="w")
label10 = Label(tab1, text="Driving license: Yes (B) Category", font=("Arial", 15, "bold"))
label10.grid(row=9, column=0, sticky="w")
label11 = Label(tab1, text="Current City: Timisoara", font=("Arial", 15, "bold"))
label11.grid(row=10, column=0, sticky="w")
label12 = Label(tab1, text="---------------------------", font=("Arial", 15, "bold"))
label12.grid(row=11, column=0, sticky="w")
label13 = Label(tab1, text="Personal Motto: Train your body for your mind (***Gym addicted***)",
                font=("Arial", 10, "bold"), fg="Red")
label13.grid(row=12, column=0, sticky="w")

label1_personal = Label(tab2, text="Personal description:", font=("Arial", 30, "bold"))
label1_personal.grid(row=0, column=0, columnspan=2)
label2_personal = Label(tab2, text="", font=("Arial", 10, "bold"))
label2_personal.grid(row=3, column=0, columnspan=2)
label3_personal = Label(tab2, text="   Hi, my name is Bogdan, and i am a self motivated person",
                        font=("Arial", 10, "bold"))
label3_personal.grid(row=4, column=0, sticky="w")
label4_personal = Label(tab2, text="I am a fast learning and i would like to learn programing Python",
                        font=("Arial", 10, "bold"))
label4_personal.grid(row=5, column=0, sticky="w")
label5_personal = Label(tab2, text="I would to become a full stack developer", font=("Arial", 10, "bold"))
label5_personal.grid(row=6, column=0, sticky="w")
label6_personal = Label(tab2, text="I would like to learn something new, this is my new challenge",
                        font=("Arial", 10, "bold"))
label6_personal.grid(row=7, column=0, sticky="w")
label7_personal = Label(tab2, text="", font=("Arial", 10, "bold"))
label7_personal.grid(row=8, column=0, columnspan=2)

label0_carer = Label(tab3, text="Process Engineer in Laser Marking", font=("Arial", 15, "bold"))
label0_carer.grid(row=0, column=0, sticky="w")
label_none_carer = Label(tab3, text="---------------------------", font=("Arial", 12, "bold"))
label_none_carer.grid(row=1, column=0, sticky="w")
label1_carer = Label(tab3, text="Polytechnic University Timisoara", font=("Arial", 15, "bold"))
label1_carer.grid(row=2, column=0, sticky="w")
label2_carer = Label(tab3, text="Faculty of Mechanics of Road Vehicles", font=("Arial", 10, "bold"))
label2_carer.grid(row=3, column=0, sticky="w")
label3_carer = Label(tab3, text="---------------------------", font=("Arial", 12, "bold"))
label3_carer.grid(row=4, column=0, sticky="w")
label3_carer = Label(tab3, text="SKILLS:", font=("Arial", 12, "bold"))
label3_carer.grid(row=5, column=0, sticky="w")
label4_carer = Label(tab3, text="* MarkingBuilder Plus/3/2 programming for Keyence Laser", font=("Arial", 10, "bold"))
label4_carer.grid(row=6, column=0, sticky="w")
label5_carer = Label(tab3, text="* Microsoft Office (Excel/Powerpoint)", font=("Arial", 10, "bold"))
label5_carer.grid(row=7, column=0, sticky="w")
label5_carer = Label(tab3, text="* Fast learning person", font=("Arial", 10, "bold"))
label5_carer.grid(row=8, column=0, sticky="w")
label6_carer = Label(tab3, text="---------------------------", font=("Arial", 12, "bold"))
label6_carer.grid(row=9, column=0, sticky="w")
label7_carer = Label(tab3, text="Special Skills:", font=("Arial", 12, "bold"))
label7_carer.grid(row=10, column=0, sticky="w")
label8_carer = Label(tab3, text="Team Leader", font=("Arial", 10, "bold"))
label8_carer.grid(row=11, column=0, sticky="w")
label9_carer = Label(tab3, text="Organized person and problem solving abilities", font=("Arial", 10, "bold"))
label9_carer.grid(row=12, column=0, sticky="w")

label1_tab = Label(tab4, text="We make day/night switching parts (SWS and HVAC) auto industry",
                   font=("Arial", 10, "bold"))
label1_tab.grid(row=0, column=0, stick="nw")
label2_tab = Label(tab4, text="*As an engineer I have to solve problems,", font=("Arial", 10, "bold"))
label2_tab.grid(row=1, column=0, stick="nw")
label2_tab = Label(tab4, text="*Make improvements (try to make parts more faster),", font=("Arial", 10, "bold"))
label2_tab.grid(row=2, column=0, stick="nw")
label3_tab = Label(tab4, text="*Ensuring the quality of parts,", font=("Arial", 10, "bold"))
label3_tab.grid(row=3, column=0, stick="nw")
label4_tab = Label(tab4, text="*Make daily meeting and monthly meeting,", font=("Arial", 10, "bold"))
label4_tab.grid(row=4, column=0, stick="nw")
label5_tab = Label(tab4, text="*Make trials (new models for production),", font=("Arial", 10, "bold"))
label5_tab.grid(row=5, column=0, stick="nw")
label6_tab = Label(tab4, text="*Communicate with other departments,", font=("Arial", 10, "bold"))
label6_tab.grid(row=6, column=0, stick="nw")
label7_tab = Label(tab4, text="*Most imp. is to understand what you have to do.", font=("Arial", 10, "bold"))
label7_tab.grid(row=7, column=0, stick="nw")


new_window.mainloop()
